# Generated by Django 6.1 on 2026-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dresses', 'Dresses'), ('tops', 'Tops'), ('accessories', 'Accessories'), ('jewellery', 'Jewellery'), ('shoes', 'Shoes')], default='dresses', max_length=50),
        ),
    ]
